-- -- Create database
-- CREATE DATABASE IF NOT EXISTS book_search;
-- USE book_search;

-- -- Table to store users
-- CREATE TABLE IF NOT EXISTS users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(255) NOT NULL UNIQUE,
--     email VARCHAR(255) NOT NULL UNIQUE,
--     password VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- -- Table to store book metadata
-- CREATE TABLE IF NOT EXISTS books (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     bookId VARCHAR(255) NOT NULL UNIQUE,
--     authors TEXT,
--     description TEXT NOT NULL,
--     image VARCHAR(255),
--     link VARCHAR(255),
--     title VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- -- Join table to track which books a user has saved
-- CREATE TABLE IF NOT EXISTS user_saved_books (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     user_id INT NOT NULL,
--     book_id INT NOT NULL,
--     UNIQUE KEY user_book_unique (user_id, book_id),
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
--     FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
-- );
